# Auto-extracted from contracts/out/PoolINFT.sol/PoolINFT.json — re-run after contract changes:
#   jq '.abi' contracts/out/PoolINFT.sol/PoolINFT.json
POOL_INFT_ABI = [
    {'inputs': [{'internalType': 'address', 'name': '_oracle', 'type': 'address'}],
     'stateMutability': 'nonpayable',
     'type': 'constructor'},
    {'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'},
                {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'approve',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'},
                {'internalType': 'address', 'name': '', 'type': 'address'}],
     'name': 'authorizations',
     'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                {'internalType': 'address', 'name': 'user', 'type': 'address'},
                {'internalType': 'uint256', 'name': 'expiresAt', 'type': 'uint256'}],
     'name': 'authorizeUsage',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'}],
     'name': 'balanceOf',
     'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [{'internalType': 'uint256', 'name': 'sourceId', 'type': 'uint256'},
                {'internalType': 'address', 'name': 'to', 'type': 'address'},
                {'internalType': 'string', 'name': 'newMetadataURI', 'type': 'string'},
                {'internalType': 'bytes', 'name': 'newSealedKey', 'type': 'bytes'},
                {'internalType': 'bytes', 'name': 'oracleSig', 'type': 'bytes'}],
     'name': 'cloneWithProof',
     'outputs': [{'internalType': 'uint256', 'name': 'newId', 'type': 'uint256'}],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'getApproved',
     'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'},
                {'internalType': 'address', 'name': 'operator', 'type': 'address'}],
     'name': 'isApprovedForAll',
     'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                {'internalType': 'address', 'name': 'user', 'type': 'address'}],
     'name': 'isAuthorized',
     'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'},
                {'internalType': 'bytes32', 'name': 'metadataHash', 'type': 'bytes32'},
                {'internalType': 'string', 'name': 'metadataURI', 'type': 'string'},
                {'internalType': 'bytes', 'name': 'sealedKey', 'type': 'bytes'}],
     'name': 'mint',
     'outputs': [{'internalType': 'uint256', 'name': 'id', 'type': 'uint256'}],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [],
     'name': 'name',
     'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [],
     'name': 'oracle',
     'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [],
     'name': 'owner',
     'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'ownerOf',
     'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
     'name': 'pools',
     'outputs': [{'internalType': 'bytes32', 'name': 'metadataHash', 'type': 'bytes32'},
                 {'internalType': 'string', 'name': 'metadataURI', 'type': 'string'},
                 {'internalType': 'bytes', 'name': 'sealedKey', 'type': 'bytes'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [],
     'name': 'renounceOwnership',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'address', 'name': 'from', 'type': 'address'},
                {'internalType': 'address', 'name': 'to', 'type': 'address'},
                {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'safeTransferFrom',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'address', 'name': 'from', 'type': 'address'},
                {'internalType': 'address', 'name': 'to', 'type': 'address'},
                {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                {'internalType': 'bytes', 'name': 'data', 'type': 'bytes'}],
     'name': 'safeTransferFrom',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'address', 'name': 'operator', 'type': 'address'},
                {'internalType': 'bool', 'name': 'approved', 'type': 'bool'}],
     'name': 'setApprovalForAll',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'address', 'name': '_o', 'type': 'address'}],
     'name': 'setOracle',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'bytes4', 'name': 'interfaceId', 'type': 'bytes4'}],
     'name': 'supportsInterface',
     'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [],
     'name': 'symbol',
     'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'tokenURI',
     'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
     'stateMutability': 'view',
     'type': 'function'},
    {'inputs': [{'internalType': 'address', 'name': 'from', 'type': 'address'},
                {'internalType': 'address', 'name': 'to', 'type': 'address'},
                {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'transferFrom',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'address', 'name': 'newOwner', 'type': 'address'}],
     'name': 'transferOwnership',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                {'internalType': 'address', 'name': 'to', 'type': 'address'},
                {'internalType': 'string', 'name': 'newMetadataURI', 'type': 'string'},
                {'internalType': 'bytes', 'name': 'newSealedKey', 'type': 'bytes'},
                {'internalType': 'bytes', 'name': 'oracleSig', 'type': 'bytes'}],
     'name': 'transferWithProof',
     'outputs': [],
     'stateMutability': 'nonpayable',
     'type': 'function'},
    {'anonymous': False,
     'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'owner', 'type': 'address'},
                {'indexed': True, 'internalType': 'address', 'name': 'approved', 'type': 'address'},
                {'indexed': True, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'Approval',
     'type': 'event'},
    {'anonymous': False,
     'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'owner', 'type': 'address'},
                {'indexed': True, 'internalType': 'address', 'name': 'operator', 'type': 'address'},
                {'indexed': False, 'internalType': 'bool', 'name': 'approved', 'type': 'bool'}],
     'name': 'ApprovalForAll',
     'type': 'event'},
    {'anonymous': False,
     'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'previous', 'type': 'address'},
                {'indexed': True, 'internalType': 'address', 'name': 'current', 'type': 'address'}],
     'name': 'OracleChanged',
     'type': 'event'},
    {'anonymous': False,
     'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'previousOwner', 'type': 'address'},
                {'indexed': True, 'internalType': 'address', 'name': 'newOwner', 'type': 'address'}],
     'name': 'OwnershipTransferred',
     'type': 'event'},
    {'anonymous': False,
     'inputs': [{'indexed': True, 'internalType': 'uint256', 'name': 'sourceId', 'type': 'uint256'},
                {'indexed': True, 'internalType': 'uint256', 'name': 'newId', 'type': 'uint256'},
                {'indexed': True, 'internalType': 'address', 'name': 'to', 'type': 'address'}],
     'name': 'PoolCloned',
     'type': 'event'},
    {'anonymous': False,
     'inputs': [{'indexed': True, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                {'indexed': True, 'internalType': 'address', 'name': 'owner', 'type': 'address'},
                {'indexed': False, 'internalType': 'bytes32', 'name': 'metadataHash', 'type': 'bytes32'},
                {'indexed': False, 'internalType': 'string', 'name': 'metadataURI', 'type': 'string'}],
     'name': 'PoolMinted',
     'type': 'event'},
    {'anonymous': False,
     'inputs': [{'indexed': True, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                {'indexed': True, 'internalType': 'address', 'name': 'from', 'type': 'address'},
                {'indexed': True, 'internalType': 'address', 'name': 'to', 'type': 'address'},
                {'indexed': False, 'internalType': 'string', 'name': 'newMetadataURI', 'type': 'string'}],
     'name': 'PoolTransferred',
     'type': 'event'},
    {'anonymous': False,
     'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'from', 'type': 'address'},
                {'indexed': True, 'internalType': 'address', 'name': 'to', 'type': 'address'},
                {'indexed': True, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'Transfer',
     'type': 'event'},
    {'anonymous': False,
     'inputs': [{'indexed': True, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                {'indexed': True, 'internalType': 'address', 'name': 'user', 'type': 'address'},
                {'indexed': False, 'internalType': 'uint256', 'name': 'expiresAt', 'type': 'uint256'}],
     'name': 'UsageAuthorized',
     'type': 'event'},
    {'inputs': [], 'name': 'ECDSAInvalidSignature', 'type': 'error'},
    {'inputs': [{'internalType': 'uint256', 'name': 'length', 'type': 'uint256'}],
     'name': 'ECDSAInvalidSignatureLength',
     'type': 'error'},
    {'inputs': [{'internalType': 'bytes32', 'name': 's', 'type': 'bytes32'}],
     'name': 'ECDSAInvalidSignatureS',
     'type': 'error'},
    {'inputs': [{'internalType': 'address', 'name': 'sender', 'type': 'address'},
                {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                {'internalType': 'address', 'name': 'owner', 'type': 'address'}],
     'name': 'ERC721IncorrectOwner',
     'type': 'error'},
    {'inputs': [{'internalType': 'address', 'name': 'operator', 'type': 'address'},
                {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'ERC721InsufficientApproval',
     'type': 'error'},
    {'inputs': [{'internalType': 'address', 'name': 'approver', 'type': 'address'}],
     'name': 'ERC721InvalidApprover',
     'type': 'error'},
    {'inputs': [{'internalType': 'address', 'name': 'operator', 'type': 'address'}],
     'name': 'ERC721InvalidOperator',
     'type': 'error'},
    {'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'}],
     'name': 'ERC721InvalidOwner',
     'type': 'error'},
    {'inputs': [{'internalType': 'address', 'name': 'receiver', 'type': 'address'}],
     'name': 'ERC721InvalidReceiver',
     'type': 'error'},
    {'inputs': [{'internalType': 'address', 'name': 'sender', 'type': 'address'}],
     'name': 'ERC721InvalidSender',
     'type': 'error'},
    {'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
     'name': 'ERC721NonexistentToken',
     'type': 'error'},
    {'inputs': [], 'name': 'NotOracleSig', 'type': 'error'},
    {'inputs': [], 'name': 'NotOwnerOrApproved', 'type': 'error'},
    {'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'}],
     'name': 'OwnableInvalidOwner',
     'type': 'error'},
    {'inputs': [{'internalType': 'address', 'name': 'account', 'type': 'address'}],
     'name': 'OwnableUnauthorizedAccount',
     'type': 'error'},
]
